version: '3.5'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev